### ISSUE TITLE
Nested routes

### ISSUE THREAD

**Issue by ansarizafar** [lukeed/svelte-demo#1]
@lukeed  Is it possible to use nested routes like vue router? If yes then could you please share an example?

**Comment by lukeed** [comment]
Don't have time for an example right now, but yes possible. That's what Navaid's `base` is for

With Navaid alone:

```js
main = (
  navaid('/')
    .on('/users', () => 'load users app/component')
    //...
);

users = (
  navaid('/users')
    .on('/:id', params => {
      console.log(`do something with User if ID: ${params.id}`);
    })
    // ...
)
```

How you slice that up in your Svelte app is completely up to you. I'd personally keep it all inside App like this demo has done

**Comment by ansarizafar** [comment]
Thanks for the sharing the code.
