### ISSUE TITLE
Ability to cancel `preload` requests

### ISSUE THREAD

**Issue by antony** [lukeed/svelte-demo#10]
Looks like the preload for the blog content can clobber other pages if it is slow to load. Since it appears that SEO wise your repo ranks quite high in google, it might be nice to upgrade to a newer version of Sapper+Svelte that don't have this issue :)

**Comment by lukeed** [comment]
Hey,

So this actually has nothing to do with the version of Svelte running (there's no Sapper). It's just that my ad-hoc `preload` implementation didn't cancel if navigation occurred _before_ the previous page's `preload` finished.

Will tinker with a fix now.
