### ISSUE TITLE
Info: Warnings in developer console

### ISSUE THREAD

**Issue by manuel3108** [lukeed/svelte-demo#11]
On every page change i got a warning the dev-console that 

> A component was created without the Attribute params

By using
```html
{#if params === undefined}
	<svelte:component this={Route}/>
{:else}
	<svelte:component this={Route} {params} />
{/if}
```
instead of 
```html 
<svelte:component this={Route} {params} />
```
in `App.svelte`, and setting `params = undefined` every time your page dost not have any params, you can get rid of this warning.

This should just be an info to those who are also annoyed, so feel free to close :D

**Comment by lukeed** [comment]
Hey, thanks :)

Warnings from the svelte compiler aren't issues or problems, necessarily -- it's just how we can notify the developer of _potential_ issues.

In this case it's the desired behavior and there's no drawback to it, so I'd rather have simpler component code than potentially convey that you _have_ to do it a more verbose way.

Will close, but thanks for double-checking :)

**Comment by frederikhors** [comment]
It's very annoying to have warnings on each navigated page.

Can we use stores for params?

**Comment by lukeed** [comment]
No, not here. In your app you can, or use the workaround mentioned above.

Keep in mind this is a demo to jumpstart/illustrate Svelte usage.

**Comment by manuel3108** [comment]
I agree with you, even if i think that production ready applications should not have those warnings. Might indicate the developer has done weird stuff.

But as mentioned above, this should just be a notice for other developers also wanting to remove them
