### ISSUE TITLE
Dynamic components removed during hydration

### ISSUE THREAD

**Issue by jimafisk** [lukeed/svelte-demo#13]
Hi @lukeed,

In my project there's [a bug](https://github.com/plentico/plenti/issues/65) where dynamic components (`<svelte:component this={route}>`) are temporarily removed during hydration on initial page load. This results in a cumulative layout shift that looks like a flash of content to the user. You can see an example of it on the website for the project: https://plenti.co/ 

Also, here are some screenshots from the default starter of the project:

<details>
<summary>Screenshot during hydration</summary>

![pmissing](https://user-images.githubusercontent.com/5913244/96391751-db27ae00-1187-11eb-821e-15f361e40155.png)

</details>

<details>
<summary>Screenshot after being fully loaded</summary>

![pfull](https://user-images.githubusercontent.com/5913244/96391756-dfec6200-1187-11eb-866f-971f91367367.png)

</details>

I initially thought this might be a [known hydration issue](https://github.com/sveltejs/svelte/issues/4308) with svelte, and even [opened an issue](https://github.com/sveltejs/svelte/issues/5470) to confirm that. However, I tried replicating hydrating dynamic components without the router and it seems to work correctly: https://github.com/jimafisk/svelte-dynamic-components

Then I pulled down the Svelte demo for Navaid (https://github.com/lukeed/svelte-demo) and noticed the same issue. Here are some screenshots:

<details>
<summary>Screenshot during hydration</summary>

![missing](https://user-images.githubusercontent.com/5913244/96391738-d06d1900-1187-11eb-8948-ea7a6060cbe7.png)

</details>

<details>
<summary>Screenshot after being fully loaded</summary>

![full](https://user-images.githubusercontent.com/5913244/96391744-d4993680-1187-11eb-921f-fa7c7de3f49f.png)

</details>

I'm curious if maybe the [Route](https://github.com/lukeed/svelte-demo/blob/master/src/components/App.svelte#L31) isn't getting set to a class constructor in time during the hydration process. Do you happen to know what might be going on here? Thanks again for all the help, and great presentation at svelte-summit today :).

**Comment by lukeed** [comment]
Hey, I moved the issue here since it's more relevant to this repo – and as discussed, it's not a Navaid bug :D

Here's an example branch on this repo, showing how to defer hydration until the first import resolves: https://github.com/lukeed/svelte-demo/commit/410388efc36e81feb16c3c41d0158a8eae29f8d9

This is the typical setup I have (and what I also set up automatically within new `freshie` apps). Routing is controlled by the boot script. And with Svelte specifically, this allows you to move/separate routing logic from the Svelte app itself, which in turn allows your server to pass in the necessary prop values to render desired content.

So, for example, you can do something like this on the server:

```js
import App from './App.js'; // built output
import * as About from './About.js'; // built output

async function render(req, Component) {
	let props = {
		params: req.params,
		Route: Component.default,
		pathname: req.path,
		// ...
	};

	if (Component.preload) {
		Object.assign(props, await Component.preload(req));
	}

	const output = App.render(props);

	// ...
}

//=> render(req, About)
```

**Comment by jimafisk** [comment]
Thanks for all the examples @lukeed! I was toying with something similar, but this really helped clarify things for me. I have a working model now: https://github.com/plentico/plenti/commit/1eccf048e2a8ffa4c36e6e4555f42753557626cf (Just need to fix an unrelated issue). I appreciate you taking the time to break things down and point me in the right direction!

**Comment by lukeed** [comment]
Not a problem, glad I could help!
