### ISSUE TITLE
Infinite fetch...

### ISSUE THREAD

**Issue by frederikhors** [lukeed/svelte-demo#2]
Something is wrong:

![image](https://user-images.githubusercontent.com/41120635/58747406-14fcf500-846b-11e9-81c9-700c3b18bc5b.png)

**Comment by lukeed** [comment]
Need to see source. Is it the code from repo unchanged?

**Comment by frederikhors** [comment]
Yeah. Just git clone.

**Comment by lukeed** [comment]
Hmm.. sorry now looking into this.

Do you know if everything is up to date? I know this _used_ to be the case, hence this commit (https://github.com/lukeed/svelte-demo/commit/43ec249674586c742fc3cefb469552048bb80faa), but I was able to revert it after a Svelte update.

I just installed this repo from scratch with fresh dependencies, and at most there are 2 fetches to the same JSON endpoint.

**Comment by lukeed** [comment]
Ah, no, you're right! I had done an exact-match installation. Somewhere been 3.0.0 and 3.4.4 this regression happened.

**Comment by frederikhors** [comment]
Can you explain it, please?

Is a Svelte related issue?

**Comment by lukeed** [comment]
Still trying to figure it out to be honest. I have issued opened, but not sure yet if I had based the work _on_ a bug, or if it not working now _is_ the bug.

**Comment by frederikhors** [comment]
Can you please re-open this so I can catch a news on it in the future? Thanks.

**Comment by lukeed** [comment]
The issue is fixed / patched for this repo. You should subscribe upstream since that's where the discussion and fix(es) will come from.

If something else needs to happen in/for this repo, I'll comment here which will notify you. But it's currently not an issue as presented
