### ISSUE TITLE
lazy loaded components get reloaded on every route change

### ISSUE THREAD

**Issue by burner** [lukeed/svelte-demo#3]
I think the title says it all. I'm not sure but I believe the router should cache what he has loaded.

btw. Nice work!

**Comment by lukeed** [comment]
Hey, thanks

What do you mean exactly? I'm running through this demo and all `chunk-*.js` files are never loaded more than once. Those are the actual components.

The `*.json` calls for Articles are happening twice per Article sometimes, but that's being discussed in #2 and in some sveltejs issues. Seems to be a recent regression, which I can fix locally here in this repo fairly easily but don't think should need to.

**Comment by burner** [comment]
I believe I spoke to soon. After rerunning it it disappeared. Sorry for the noise.

**Comment by lukeed** [comment]
Not a problem! Better safe than sorry~
