### ISSUE TITLE
Blog page doesn't open

### ISSUE THREAD

**Issue by jakobrosenberg** [lukeed/svelte-demo#4]
The other pages do though.

**Comment by lukeed** [comment]
Hmm maybe something changed in recent versions.
What version of Svelte are you using? And are there any errors in console?

**Comment by jakobrosenberg** [comment]
```Access to fetch at 'https://sapper-template.now.sh/blog.json' from origin 'http://localhost:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

I just ran npm install, so I assume the latest version of Svelte.

**Comment by lukeed** [comment]
Oh, the sapper demo no longer lives there. I'll see if I can track down its current URL
