### ISSUE TITLE
Decode URI for the params

### ISSUE THREAD

**Issue by nitroboy720** [lukeed/svelte-demo#7]
For url parameters that have some special characters encoded in, you should decode them before setting them as the params.

For example, on a login page that has a `nextUrl` to redirect to, the `nextUrl` param probably has some special characters that need decoding.

Solution would be rather simple, juste use the function `decodeURIComponent()` on each of the received params.  

Edit: I should probably have posted this on the navaid repo itself

**Comment by lukeed** [comment]
Hey,

This is a basic, overly simplistic demo.
Decoding (or not decoding) is specific to your app. 

This applies to navaid too & it's why it doesn't auto-decode by default. Your app may (or may not) want that.

Thank you though :)
